### PR TITLE
Update .thoth.yaml

### PR DESCRIPTION
**Pull request by saisankargochhayat**
Depends on #14

### CODE REVIEW

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
@saisankargochhayat could you have a look at the root cause for the coals errors and open another PR fixing them? Then let this PR Depends-On: the other PR? :)

**Comment by saisankargochhayat** [comment]
> @saisankargochhayat could you have a look at the root cause for the coals errors and open another PR fixing them? Then let this PR Depends-On: the other PR? :)

Please merge #14 to get coala fixes.

**Comment by goern** [comment]
Recheck

**Pull request merged**
